### ISSUE TITLE
unable to get the app working

### ISSUE THREAD

**Issue by pradeepgovindaswamy** [animeshp/SampleHomeKit#1]
Animesh i have added the accessories using the homekit accessory simulator and when i run the SampleHomeKit app it asks to create a home after which when i click add accessories which starts the discovery of the homekit accessories it never returns back meaning it doesn't list the accessories at all and doesn't come to the delegate. Could you kindly let me know what else needs to be done to get the app list the accessories?
I have been using the xcode 6 beta which comes with homekit accessory simulator with it.

**Comment by animeshp** [comment]
@pradeepgovindaswamy which xcode beta version are you using? I wrote this code using beta 1 and now there are lots of changes. I 'm in the process of updating the code. 

Meanwhile, are you getting any error while searching for accessories?

**Comment by mayur-who** [comment]
cannot compile only, i am getting ServiceDetailsViewController.m:84:60: Use of undeclared identifier 'HMCharacteristicTypeLocked'

**Comment by zlDev** [comment]
I'm here with @mayurcools, getting the same error.

**Comment by tbfly** [comment]
@animeshp  don't work with the released 8.1 SDK.

HMCharacteristicTypeLocked should revise.

**Comment by spideronly** [comment]
i am having the same issue

**Comment by tbfly** [comment]
@spideronly 

You can try my patch:
https://github.com/animeshp/SampleHomeKit/pull/2

**Comment by animeshp** [comment]
@tbfly merged your change into existing code. Thanks for the help. 
@all 
Now i'm working on this app to improve it. Didn't get time to work on this. I was busy in some other projects. The app should be compilable and working now.

Thanks.
